### ISSUE TITLE
Start synchronization don't count properly

### ISSUE THREAD

**Issue by squakez** [camel-tooling/camel-dashboard-operator#37]
When we restart an operator, the first time we calculate the SLI, it reports negative values:

```
  sliExchangeSuccessRate:
    samplingInterval: 60000000000
    samplingIntervalFailed: -545
    samplingIntervalTotal: -4944
```

This is likely because we need to skip this calculation when there is not yet available the exchange metrics.
